// !!! DO NOT EDIT THIS FILE !!!

// ==============================================
// Commons settings for Consul
// ==============================================
log_level = "DEBUG"
disable_update_check = true

// ==============================================
// Addresses & Ports
// See: https://developer.hashicorp.com/consul/docs/agent/config/config-files#advertise-address-parameters
// ==============================================
// The "eth0" interface is "consul_area_lan" network
advertise_addr  = "{{ GetInterfaceIP \"eth0\" }}"
bind_addr       = "0.0.0.0" // or "{{ GetInterfaceIP \"eth0\" }}"
client_addr     = "0.0.0.0"

// ==============================================
// Server
// See: https://developer.hashicorp.com/consul/docs/agent/config/config-files#bootstrap-parameters
// ==============================================
server = true
bootstrap_expect = 3
retry_join = ["server", "server", "server"]
retry_max = 30 // By default, this is set to 0 which is interpreted as infinite retries
retry_interval = "30s" // Defaults to 30s
rejoin_after_leave = false
leave_on_terminate = true

// It is recommended to configure the server performance parameters back to Consul's original high-performance settings.
// This will let Consul servers detect a failed leader and complete leader elections much more quickly than the default configuration
// which extends key Raft timeouts by a factor of 5, so it can be quite slow during these events.
// 
// See https://developer.hashicorp.com/consul/docs/install/performance#production
performance {
    raft_multiplier = 1
}

// See: https://developer.hashicorp.com/consul/docs/agent/config/config-files#autopilot
autopilot {
    server_stabilization_time = "10s"
    last_contact_threshold = "200ms"
    max_trailing_logs = 250
    cleanup_dead_servers = true
}

// See: https://developer.hashicorp.com/consul/docs/agent/config/config-files#limits
limits {
    // Configures the limit for how long a client is allowed to read from an RPC connection.
    // This is used to set an upper bound for calls to eventually terminate so that RPC connections are not held indefinitely.
    // Blocking queries can override this timeout. Default is 60s.
    rpc_client_timeout = "120s"
}
